import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const matches = sqliteTable(
  "matches",
  {
    id: text("id").primaryKey(),
    source: text("source").notNull(),
    sourceKey: text("source_key").notNull(),
    fileName: text("file_name"),
    competition: text("competition").notNull(),
    season: text("season").notNull(),
    matchDate: text("match_date").notNull(),
    kickoff: text("kickoff"),
    homeTeam: text("home_team").notNull(),
    awayTeam: text("away_team").notNull(),
    homeKey: text("home_key").notNull(),
    awayKey: text("away_key").notNull(),
    homeGoals: integer("home_goals"),
    awayGoals: integer("away_goals"),
    result: text("result"),
    referee: text("referee"),
    homeShots: integer("home_shots"),
    awayShots: integer("away_shots"),
    homeShotsTarget: integer("home_shots_target"),
    awayShotsTarget: integer("away_shots_target"),
    homeCorners: integer("home_corners"),
    awayCorners: integer("away_corners"),
    homeYellow: integer("home_yellow"),
    awayYellow: integer("away_yellow"),
    homeRed: integer("home_red"),
    awayRed: integer("away_red"),
    oddsHome: real("odds_home"),
    oddsDraw: real("odds_draw"),
    oddsAway: real("odds_away"),
    importedAt: text("imported_at").notNull(),
  },
  (table) => [
    uniqueIndex("matches_source_key_unique").on(table.sourceKey),
    index("matches_date_idx").on(table.matchDate),
    index("matches_home_key_idx").on(table.homeKey),
    index("matches_away_key_idx").on(table.awayKey),
    index("matches_competition_season_idx").on(table.competition, table.season),
  ],
);

export const importJobs = sqliteTable(
  "import_jobs",
  {
    id: text("id").primaryKey(),
    source: text("source").notNull(),
    fileName: text("file_name").notNull(),
    season: text("season").notNull(),
    status: text("status").notNull(),
    rowsTotal: integer("rows_total").notNull(),
    rowsImported: integer("rows_imported").notNull(),
    rowsSkipped: integer("rows_skipped").notNull(),
    rowsInvalid: integer("rows_invalid").notNull(),
    createdAt: text("created_at").notNull(),
  },
  (table) => [index("import_jobs_created_at_idx").on(table.createdAt)],
);

export const predictions = sqliteTable(
  "predictions",
  {
    id: text("id").primaryKey(),
    predictionKey: text("prediction_key").notNull(),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    kickoff: text("kickoff"),
    matchDate: text("match_date").notNull(),
    competition: text("competition").notNull(),
    homeTeam: text("home_team").notNull(),
    awayTeam: text("away_team").notNull(),
    homeKey: text("home_key").notNull(),
    awayKey: text("away_key").notNull(),
    recommendation: text("recommendation").notNull(),
    predictedOutcome: text("predicted_outcome"),
    probabilityHome: real("probability_home"),
    probabilityDraw: real("probability_draw"),
    probabilityAway: real("probability_away"),
    oddsHome: real("odds_home"),
    oddsDraw: real("odds_draw"),
    oddsAway: real("odds_away"),
    modelVersion: text("model_version").notNull(),
    status: text("status").notNull(),
    actualResult: text("actual_result"),
    correct: integer("correct"),
    profit: real("profit"),
    settledAt: text("settled_at"),
  },
  (table) => [
    uniqueIndex("predictions_key_unique").on(table.predictionKey),
    index("predictions_status_date_idx").on(table.status, table.matchDate),
    index("predictions_match_idx").on(table.competition, table.matchDate, table.homeKey, table.awayKey),
  ],
);
